# SMA INDICATOR
SMA_long = 1000
SMA_short = 50

#Sell At % of atr
takeAt = 10
stopAt = 10

#ATR
ATR_Period = 10

# RSI BULL / BEAR
BULL_RSI = 10
BULL_RSI_high = 80
BULL_RSI_low = 60

BEAR_RSI = 15
BEAR_RSI_high = 50
BEAR_RSI_low = 20

# BBANDS
Bull_BB_Time = 20
Bull_BB_DevUp = 2
Bull_BB_DevDown = 2

Bear_BB_Time = 20
Bear_BB_DevUp = 2
Bear_BB_DevDown = 2

# MODIFY RSI (depending on ADX)
BULL_MOD_high = 5
BULL_MOD_low = -5
BEAR_MOD_high = 15
BEAR_MOD_low = -5

# ADX
ADX = 3
ADX_high = 70
ADX_low = 50
