# default

# SMA Trends
SMA_long = 1000
SMA_short = 50

# BULL
BULL_RSI = 10
BULL_RSI_high = 80
BULL_RSI_low = 60

# BEAR
BEAR_RSI = 15
BEAR_RSI_high = 50
BEAR_RSI_low = 20

# ADX
ADX = 3
ADX_high = 70
ADX_low = 50


# # from discord
# # SMA Trends
# SMA_long = 500
# SMA_short = 20
#
# # BULL
# BULL_RSI = 10
# BULL_RSI_high = 90
# BULL_RSI_low = 40
#
# # BEAR
# BEAR_RSI = 15
# BEAR_RSI_high = 50
# BEAR_RSI_low = 20
#
# # ADX
# ADX = 3
# ADX_high = 70
# ADX_low = 50
